name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    environment: main
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: build
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: jessecorson/jessecorson.com
        TARGET_BRANCH: main
        BUILD_SCRIPT: make build
        BUILD_DIR: .vuepress/dist/
    - name: sync
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'       # optional: defaults to us-east-1
        SOURCE_DIR: '.vuepress/dist/' # optional: defaults to entire repository
